name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TABIDOO_API_KEY: ${{ secrets.TABIDOO_API_KEY }} 
      TABIDOO_APP_NAME: ${{ vars.TABIDOO_APP_NAME }} 
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }} 
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }} 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Build the application
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
